version: "2"
services:
  basecommon:
    build:
      context: .
      dockerfile: ./resources/docker/base/common/Dockerfile
    image: base-common
  basenginx:
    build:
      context: .
      dockerfile: ./resources/docker/base/nginx/Dockerfile
    image: base-nginx
  basephp7:
    build:
      context: .
      dockerfile: ./resources/docker/base/php7/Dockerfile
    image: base-php7
  systemnginx:
    build:
      context: .
      dockerfile: ./resources/docker/system/nginx/Dockerfile
    image: system-nginx
  systemphp7:
    build:
      context: .
      dockerfile: ./resources/docker/system/php7/Dockerfile
    image: system-php7
  businessphp7a01api:
    build:
      context: .
      dockerfile: ./resources/docker/business/php7a01api/Dockerfile
      args:
        - MODULE_PORT=7100
    image: business-php7a01api
    ports:
      - "7100"
    command: -n sy_api -s start -module a01api -port 7100